---

- name: Deploy to the powerboard
  hosts: THUNDERBOTS_HOSTS

  tasks:
    - name: Sync powerboard files
      become: true
      become_method: sudo
      ansible.posix.synchronize:
        src: ../../../../../power/powerloop.tar.gz
        dest: ~/
        recursive: yes
        copy_links: yes

    - name: Untar powerboard files
      command: 'mkdir -p powerloop && tar -xvf ~/powerloop.tar.gz -C powerloop'
      register: result
      args:
        chdir: ~/

    - name: Hold boot and press reset on the powerboards to enter bootloader mode.
      ansible.builtin.pause:
        prompt: "Press enter to continue"
        echo: no

    - name: Flashing...
      shell: '/opt/tbotspython/bin/platformio run -s -t upload -d ~/powerloop/power'
      register: result

    - name: Reset powerboard to finish flashing
      ansible.builtin.pause:
        prompt: "Press enter to continue"
        echo: no
